window.NORTHE_SCRIPT_DATA = {
  "id": "yin-yang-outubro-2026",
  "cycle": "Outubro 2026",
  "storageKey": "yy-review-outubro-2026-v1",
  "reviewLabel": "Roteiro final",
  "client": {
    "name": "Espaço YinYang"
  },
  "scripts": [
    {
      "id": "P01",
      "displayId": "01",
      "section": "ROTEIROS PRINCIPAIS",
      "sectionDescription": "12 Reels · Talking Head · retenção + transformação",
      "kind": "Reel",
      "date": "Outubro 2026",
      "title": "Você não odeia conflito",
      "role": "Crescimento / visualização",
      "idea": "A pessoa acha que evita conflito por ser tranquila, mas percebe que pode estar evitando rejeição.",
      "format": "Reel · Talking Head · 30–45s",
      "text": "Você discorda de alguém, percebe que a pessoa ficou chateada… e imediatamente começa a voltar atrás.\n\nTalvez você não odeie conflito. Talvez tenha medo do que acontece depois dele.\n\nAí você concorda, releva, deixa passar e chama isso de “manter a paz”. Só que, aos poucos, começa a precisar se abandonar para manter algumas relações.\n\nÉ aí que o medo de rejeição vira um problema: você preserva o vínculo, mas sempre às suas custas.\n\nPaz não é nunca discordar. É descobrir que uma relação saudável consegue sobreviver quando você pensa diferente.\n\nSe você gosta desse olhar sobre psicoterapia e relacionamentos, me segue.\n\nCORTE CURTO\n“Talvez você não evite conflito. Talvez evite a possibilidade de ser rejeitado.”\n\nPALAVRAS-CHAVE\nmedo de rejeição · relacionamentos · psicoterapia"
    },
    {
      "id": "P02",
      "displayId": "02",
      "section": "ROTEIROS PRINCIPAIS",
      "kind": "Reel",
      "date": "Outubro 2026",
      "title": "Você não está “pensando melhor”",
      "role": "Crescimento / busca",
      "idea": "Overthinking deixa de parecer excesso de análise e passa a ser visto como busca por uma decisão sem risco.",
      "format": "Reel · Talking Head · 30–45s",
      "text": "Você toma uma decisão. Cinco minutos depois pergunta para um amigo. Depois para outro. Pesquisa mais um pouco… e volta exatamente para onde começou.\n\nTalvez você não esteja procurando a melhor decisão.\n\nTalvez esteja procurando uma decisão sem risco.\n\nÉ aí que o overthinking prende você: quanto mais tenta eliminar qualquer chance de arrependimento, mais possibilidades aparecem e menos consegue escolher.\n\nA ansiedade promete: “pensa só mais um pouco e você vai ter certeza”.\n\nSó que algumas decisões não vêm com certeza.\n\nÀs vezes decidir também é aceitar que você não controla tudo que acontece depois.\n\nSe você vive pensando demais, me segue.\n\nCORTE CURTO\n“Talvez você não queira tomar a decisão certa. Talvez queira uma decisão sem risco.”\n\nPALAVRAS-CHAVE\noverthinking · ansiedade · indecisão"
    },
    {
      "id": "P03",
      "displayId": "03",
      "section": "ROTEIROS PRINCIPAIS",
      "kind": "Reel",
      "date": "Outubro 2026",
      "title": "A mensagem que não chega",
      "role": "Crescimento / identificação",
      "idea": "Uma mensagem sem resposta vira uma história inteira antes de qualquer fato acontecer.",
      "format": "Reel · Talking Head · 30–45s",
      "text": "Você manda uma mensagem. A pessoa demora para responder e, meia hora depois, você já está relendo a conversa procurando o que fez de errado.\n\nE o mais estranho é que nada aconteceu ainda.\n\nVocê olha o horário, pensa se falou demais, se pareceu carente, se a pessoa perdeu o interesse.\n\nO silêncio vira uma resposta antes mesmo da resposta chegar.\n\nÉ assim que ansiedade e medo de rejeição podem entrar numa relação: você começa a reagir não ao que aconteceu, mas ao que imagina que pode acontecer.\n\nTalvez o desafio seja aprender a suportar alguns minutos de silêncio sem transformá-los em abandono.\n\nSe isso acontece com você, me segue.\n\nCORTE CURTO\n“O silêncio vira uma resposta antes mesmo da resposta chegar.”\n\nPALAVRAS-CHAVE\nansiedade · medo de rejeição · relacionamento · apego"
    },
    {
      "id": "P04",
      "displayId": "04",
      "section": "ROTEIROS PRINCIPAIS",
      "kind": "Reel",
      "date": "Outubro 2026",
      "title": "Isso é química mesmo?",
      "role": "Crescimento / compartilhamento",
      "idea": "A imprevisibilidade de uma relação pode ser confundida com química e conexão.",
      "format": "Reel · Talking Head · 30–45s",
      "text": "A pessoa some por dois dias. Volta. Você sente aquele frio na barriga. Some de novo… e você pensa nela ainda mais.\n\nIsso parece química.\n\nMas e se parte dessa intensidade for a ansiedade de tentar ser escolhido?\n\nQuando você nunca sabe quando vai receber atenção de novo, cada pequena demonstração ganha um peso enorme.\n\nE aí intensidade começa a parecer conexão.\n\nSó que intimidade não deveria exigir que você passe o tempo inteiro tentando descobrir se o outro ainda quer você.\n\nÀs vezes o que parecia paixão era a tensão de nunca saber onde estava pisando.\n\nSe você gosta de falar sobre relacionamentos e psicoterapia dessa forma, me segue.\n\nCORTE CURTO\n“Nem toda intensidade é intimidade.”\n\nPALAVRAS-CHAVE\ndependência emocional · relacionamentos · ansiedade · apego"
    },
    {
      "id": "P05",
      "displayId": "05",
      "section": "ROTEIROS PRINCIPAIS",
      "kind": "Reel",
      "date": "Outubro 2026",
      "title": "Isso não é limite",
      "role": "Crescimento / autoridade",
      "idea": "Limite deixa de ser ameaça ao outro e passa a ser responsabilidade pela própria escolha.",
      "format": "Reel · Talking Head · 30–45s",
      "text": "“Se você fizer isso de novo, eu nunca mais falo com você.”\n\nA frase parece um limite. Mas ainda existe um problema: sua decisão continua dependendo do comportamento do outro.\n\nLimite não é convencer alguém a mudar.\n\nÉ decidir o que você faz quando uma situação ultrapassa aquilo que consegue aceitar.\n\nPor isso existe diferença entre “você não pode fazer isso comigo” e “se isso continuar, eu não permaneço nessa situação”.\n\nNum você tenta controlar a pessoa.\n\nNo outro, assume responsabilidade pela sua escolha.\n\nE essa diferença muda muita coisa numa relação.\n\nSe você gosta de falar sobre limites e relacionamentos sem frase pronta de internet, me segue.\n\nCORTE CURTO\n“Limite não é uma regra que você cria para controlar outra pessoa.”\n\nPALAVRAS-CHAVE\nlimites · relacionamento tóxico · psicoterapia · relacionamentos"
    },
    {
      "id": "P06",
      "displayId": "06",
      "section": "ROTEIROS PRINCIPAIS",
      "kind": "Reel",
      "date": "Outubro 2026",
      "title": "Você já entendeu. E fez de novo.",
      "role": "Crescimento / psicoterapia",
      "idea": "Saber explicar um padrão não significa conseguir agir diferente quando ele aparece.",
      "format": "Reel · Talking Head · 30–45s",
      "text": "Você já sabe que corre atrás de gente indisponível. Já sabe que foge quando alguém se aproxima. Já sabe até de onde isso pode ter vindo.\n\nE ontem fez tudo de novo.\n\nEsse é um dos pontos mais frustrantes do autoconhecimento.\n\nPorque entender o padrão não significa que você consegue agir diferente quando ele aparece.\n\nA mudança começa naquele segundo em que a situação real acontece e você percebe: “eu conheço esse caminho”.\n\nSó que, dessa vez, existe a possibilidade de escolher outra resposta.\n\nPsicoterapia não deveria servir apenas para explicar quem você é.\n\nEla também precisa abrir espaço para você deixar de repetir algumas coisas.\n\nSe você gosta dessa abordagem, me segue.\n\nCORTE CURTO\n“Saber o nome do padrão não quebra o padrão.”\n\nPALAVRAS-CHAVE\nautossabotagem · autoconhecimento · psicoterapia · padrões emocionais"
    },
    {
      "id": "P07",
      "displayId": "07",
      "section": "ROTEIROS PRINCIPAIS",
      "kind": "Reel",
      "date": "Outubro 2026",
      "title": "O corpo cansou. A cabeça não.",
      "role": "Crescimento / busca",
      "idea": "Cansaço físico e mente em estado de alerta aparecem como coisas diferentes.",
      "format": "Reel · Talking Head · 30–45s",
      "text": "Você passa o dia inteiro pensando que só queria chegar em casa e dormir.\n\nAí deita… e sua cabeça começa a lembrar de tudo que poderia ter lembrado oito horas antes.\n\nA conversa de ontem. O trabalho de amanhã. A coisa que pode dar errado semana que vem.\n\nSeu corpo está cansado. Mas sua mente continua procurando alguma coisa para resolver.\n\nEm períodos de ansiedade e estresse, esse estado de alerta pode continuar mesmo quando você finalmente parou.\n\nTalvez descansar não seja apenas deitar.\n\nTalvez seja aprender a mostrar para a sua cabeça que, naquele momento, não existe nada que ela precise resolver.\n\nSe você conhece essa sensação, me segue.\n\nCORTE CURTO\n“Seu corpo pode estar exausto enquanto sua cabeça ainda acha que existe alguma coisa para resolver.”\n\nPALAVRAS-CHAVE\nansiedade · estresse · mente acelerada · esgotamento emocional"
    },
    {
      "id": "P08",
      "displayId": "08",
      "section": "ROTEIROS PRINCIPAIS",
      "kind": "Reel",
      "date": "Outubro 2026",
      "title": "Se eu sinto falta, talvez eu deva voltar",
      "role": "Crescimento / relacionamento",
      "idea": "Saudade deixa de ser tratada como prova de que o término foi um erro.",
      "format": "Reel · Talking Head · 30–45s",
      "text": "Você sabe que aquela relação te fazia mal.\n\nMas aí bate saudade… e, de repente, você começa a questionar se terminar foi mesmo a decisão certa.\n\nEsse é o problema: saudade não faz uma avaliação completa da relação.\n\nEla lembra da companhia, da rotina, dos momentos bons e até daquilo que você esperava que um dia melhorasse.\n\nE por alguns minutos tudo que machucava fica pequeno.\n\nÉ por isso que sentir falta não significa que voltar é uma boa decisão.\n\nVocê pode amar alguém, sentir saudade e ainda reconhecer que aquela relação não fazia bem para você.\n\nSe você está passando por um término ou dependência emocional, me segue.\n\nCORTE CURTO\n“Sentir falta de alguém não significa que aquela pessoa fazia bem para você.”\n\nPALAVRAS-CHAVE\ndependência emocional · término · relacionamento tóxico · relacionamentos"
    },
    {
      "id": "P09",
      "displayId": "09",
      "section": "ROTEIROS PRINCIPAIS",
      "kind": "Reel",
      "date": "Outubro 2026",
      "title": "Você pede desculpa até sem ter errado",
      "role": "Crescimento / identificação",
      "idea": "O pedido de desculpas automático pode revelar medo de incomodar e ocupar espaço.",
      "format": "Reel · Talking Head · 30–45s",
      "text": "“Desculpa incomodar.”\n\n“Desculpa perguntar.”\n\n“Desculpa falar isso.”\n\nTem gente que pede desculpa antes mesmo de fazer qualquer coisa errada.\n\nE talvez isso não seja só educação.\n\nPorque, quando você aprende que incomodar, discordar ou precisar de alguma coisa pode afastar alguém, começa a tentar ocupar cada vez menos espaço.\n\nA desculpa vira quase uma forma de pedir permissão para existir naquela relação.\n\nGentileza é uma coisa.\n\nSentir que suas necessidades sempre precisam vir acompanhadas de culpa é outra.\n\nSe você percebeu que faz isso, comenta um ☯️ aqui embaixo.\n\nCORTE CURTO\n“Talvez você não peça desculpa porque errou. Talvez peça porque tem medo de incomodar.”\n\nPALAVRAS-CHAVE\nautoestima · people pleasing · medo de rejeição · relacionamentos"
    },
    {
      "id": "P10",
      "displayId": "10",
      "section": "ROTEIROS PRINCIPAIS",
      "kind": "Reel",
      "date": "Outubro 2026",
      "title": "Quando a pessoa te quer, você não quer mais",
      "role": "Crescimento / relacionamento",
      "idea": "A queda de interesse pode ser a queda da ansiedade de conquistar, não necessariamente da conexão.",
      "format": "Reel · Talking Head · 30–45s",
      "text": "Enquanto você não sabe se a pessoa gosta de você, pensa nela o dia inteiro.\n\nAí ela começa a demonstrar interesse de verdade… e alguma coisa esfria.\n\nVocê chama isso de “perder a química”.\n\nMas talvez o que tenha desaparecido não seja o interesse.\n\nTalvez tenha desaparecido a ansiedade de tentar conquistar aquela pessoa.\n\nPorque desejar alguém distante permite fantasiar.\n\nQuando existe reciprocidade, aparece outra coisa: intimidade. E agora você também pode ser conhecido, frustrado ou rejeitado de verdade.\n\nAlguns padrões de apego ficam muito mais visíveis justamente quando alguém finalmente se aproxima.\n\nSe você se reconheceu nisso, me segue.\n\nCORTE CURTO\n“Talvez você não tenha perdido o interesse. Talvez tenha perdido a ansiedade de conquistar.”\n\nPALAVRAS-CHAVE\napego · relacionamentos · autossabotagem · intimidade"
    },
    {
      "id": "P11",
      "displayId": "11",
      "section": "ROTEIROS PRINCIPAIS",
      "kind": "Reel",
      "date": "Outubro 2026",
      "title": "Tomara que cancelem",
      "role": "Crescimento / identificação",
      "idea": "O alívio de um compromisso cancelado pode dizer mais sobre a sobrecarga do que sobre o compromisso.",
      "format": "Reel · Talking Head · 30–45s",
      "text": "Você marca de sair na sexta.\n\nNa segunda está animado.\n\nNa quinta já começa a pensar numa desculpa.\n\nNa sexta chega uma mensagem: “não vou conseguir ir”.\n\nE você sente um alívio enorme.\n\nUma vez ou outra, normal.\n\nMas quando cancelar planos vira uma das poucas coisas que traz alívio, talvez o problema não seja aquele compromisso.\n\nPode existir sobrecarga, ansiedade social, cansaço ou uma rotina que deixa você sem espaço nenhum antes mesmo do lazer chegar.\n\nSe você precisa que as coisas sejam canceladas para finalmente descansar, talvez esteja faltando descanso antes do limite.\n\nSe isso acontece muito com você, deixa um ☯️.\n\nCORTE CURTO\n“Se cancelar planos é uma das únicas coisas que te dá alívio, talvez o problema não seja o plano.”\n\nPALAVRAS-CHAVE\nansiedade social · sobrecarga · esgotamento · saúde mental"
    },
    {
      "id": "P12",
      "displayId": "12",
      "section": "ROTEIROS PRINCIPAIS",
      "kind": "Reel",
      "date": "Outubro 2026",
      "title": "O que você não conta na terapia",
      "role": "Crescimento / intenção",
      "idea": "O medo de julgamento dentro da própria terapia vira parte daquilo que precisa ser trabalhado.",
      "format": "Reel · Talking Head · 30–45s",
      "text": "Você chega na terapia sabendo exatamente o que aconteceu.\n\nConta a semana inteira… e pula justamente a parte que mais te envergonha.\n\nTalvez essa parte seja a sessão.\n\nPorque às vezes você não esconde algo porque acha irrelevante.\n\nEsconde porque tem medo de que até o psicoterapeuta pense diferente de você depois de ouvir aquilo.\n\nE aí surge uma coisa interessante: o mesmo medo de julgamento que aparece lá fora começa a aparecer dentro da própria terapia.\n\nVocê não precisa contar tudo antes de se sentir seguro.\n\nMas aquilo que parece impossível de dizer pode mostrar exatamente onde o vínculo terapêutico precisa chegar.\n\nSe você já faz psicoterapia, me segue.\n\nCORTE CURTO\n“Talvez aquilo que você não consegue contar na terapia seja justamente o que precisa entrar nela.”\n\nPALAVRAS-CHAVE\npsicoterapia · terapia · psicoterapeuta · vínculo terapêutico"
    },
    {
      "id": "M01",
      "displayId": "01",
      "section": "MICROCONTEÚDOS",
      "sectionDescription": "12 peças · 3–10s · ação simples + pensamento seco",
      "kind": "Micro",
      "date": "Outubro 2026",
      "title": "Conflito",
      "role": "Microconteúdo / reflexão",
      "idea": "Uma pergunta curta que desloca o conflito do ato de discutir para o medo de rejeição.",
      "format": "Micro Reel · 3–10s · ação + fala",
      "bodyLabel": "AÇÃO + FALA",
      "reviewLabel": "Microconteúdo",
      "text": "AÇÃO\nDelilton mexendo em alguma coisa na mesa. Para, olha para a câmera.\n\nFALA\n“E se você não evitar conflitos… e sim a possibilidade de ser rejeitado?”\n\nFIM."
    },
    {
      "id": "M02",
      "displayId": "02",
      "section": "MICROCONTEÚDOS",
      "kind": "Micro",
      "date": "Outubro 2026",
      "title": "Decisão",
      "role": "Microconteúdo / reflexão",
      "idea": "Transformar a indecisão em uma pergunta sobre risco, não sobre acerto.",
      "format": "Micro Reel · 3–10s · ação + fala",
      "bodyLabel": "AÇÃO + FALA",
      "reviewLabel": "Microconteúdo",
      "text": "AÇÃO\nDelilton escrevendo em um caderno. Para no meio e olha para a câmera.\n\nFALA\n“Talvez você não queira tomar a decisão certa. Talvez queira uma decisão sem risco.”\n\nFIM."
    },
    {
      "id": "M03",
      "displayId": "03",
      "section": "MICROCONTEÚDOS",
      "kind": "Micro",
      "date": "Outubro 2026",
      "title": "Silêncio",
      "role": "Microconteúdo / reflexão",
      "idea": "Fazer a pessoa perceber quanto significado cria antes da resposta existir.",
      "format": "Micro Reel · 3–10s · ação + fala",
      "bodyLabel": "AÇÃO + FALA",
      "reviewLabel": "Microconteúdo",
      "text": "AÇÃO\nDelilton olha rapidamente para o celular, deixa ele de lado e olha para a câmera.\n\nFALA\n“Já percebeu que, às vezes, o silêncio vira uma resposta antes mesmo da resposta chegar?”\n\nFIM."
    },
    {
      "id": "M04",
      "displayId": "04",
      "section": "MICROCONTEÚDOS",
      "kind": "Micro",
      "date": "Outubro 2026",
      "title": "Intensidade",
      "role": "Microconteúdo / reflexão",
      "idea": "Uma frase seca que separa intensidade de intimidade.",
      "format": "Micro Reel · 3–10s · ação + fala",
      "bodyLabel": "AÇÃO + FALA",
      "reviewLabel": "Microconteúdo",
      "text": "AÇÃO\nDelilton lendo um livro. Abaixa um pouco o livro e olha para a câmera.\n\nFALA\n“Você sabia que nem toda intensidade é intimidade?”\n\nFIM."
    },
    {
      "id": "M05",
      "displayId": "05",
      "section": "MICROCONTEÚDOS",
      "kind": "Micro",
      "date": "Outubro 2026",
      "title": "Limites",
      "role": "Microconteúdo / reflexão",
      "idea": "Uma provocação curta sobre quando o limite ainda está tentando controlar o outro.",
      "format": "Micro Reel · 3–10s · ação + fala",
      "bodyLabel": "AÇÃO + FALA",
      "reviewLabel": "Microconteúdo",
      "text": "AÇÃO\nDelilton organizando alguns papéis. Para e olha para a câmera.\n\nFALA\n“E se o seu limite estiver tentando controlar o outro… talvez ele não seja um limite.”\n\nFIM."
    },
    {
      "id": "M06",
      "displayId": "06",
      "section": "MICROCONTEÚDOS",
      "kind": "Micro",
      "date": "Outubro 2026",
      "title": "Padrões",
      "role": "Microconteúdo / reflexão",
      "idea": "Separar compreender um padrão de realmente interrompê-lo.",
      "format": "Micro Reel · 3–10s · ação + fala",
      "bodyLabel": "AÇÃO + FALA",
      "reviewLabel": "Microconteúdo",
      "text": "AÇÃO\nDelilton escrevendo alguma coisa. Fecha o caderno.\n\nFALA\n“Entender por que você repete um padrão não significa que você parou de repeti-lo.”\n\nFIM."
    },
    {
      "id": "M07",
      "displayId": "07",
      "section": "MICROCONTEÚDOS",
      "kind": "Micro",
      "date": "Outubro 2026",
      "title": "Cansaço",
      "role": "Microconteúdo / reflexão",
      "idea": "Colocar em uma frase a diferença entre corpo exausto e mente em alerta.",
      "format": "Micro Reel · 3–10s · ação + fala",
      "bodyLabel": "AÇÃO + FALA",
      "reviewLabel": "Microconteúdo",
      "text": "AÇÃO\nDelilton tira os óculos, passa a mão no rosto ou encosta na cadeira como quem está cansado.\n\nFALA\n“Seu corpo pode estar exausto enquanto sua cabeça ainda acha que precisa resolver alguma coisa.”\n\nFIM."
    },
    {
      "id": "M08",
      "displayId": "08",
      "section": "MICROCONTEÚDOS",
      "kind": "Micro",
      "date": "Outubro 2026",
      "title": "Saudade",
      "role": "Microconteúdo / reflexão",
      "idea": "Separar saudade da conclusão de que a relação fazia bem.",
      "format": "Micro Reel · 3–10s · ação + fala",
      "bodyLabel": "AÇÃO + FALA",
      "reviewLabel": "Microconteúdo",
      "text": "AÇÃO\nDelilton olhando alguma coisa fora de quadro. Depois olha para a câmera.\n\nFALA\n“Sentir falta de alguém não significa que aquela pessoa fazia bem para você.”\n\nFIM."
    },
    {
      "id": "M09",
      "displayId": "09",
      "section": "MICROCONTEÚDOS",
      "kind": "Micro",
      "date": "Outubro 2026",
      "title": "Desculpas",
      "role": "Microconteúdo / reflexão",
      "idea": "Levar a pessoa a questionar se o pedido de desculpas nasce do erro ou do medo de incomodar.",
      "format": "Micro Reel · 3–10s · ação + fala",
      "bodyLabel": "AÇÃO + FALA",
      "reviewLabel": "Microconteúdo",
      "text": "AÇÃO\nDelilton começa a fazer alguma coisa, para como se tivesse lembrado de algo e olha para a câmera.\n\nFALA\n“E se você pedir desculpa não porque errou… mas porque tem medo de incomodar?”\n\nFIM."
    },
    {
      "id": "M10",
      "displayId": "10",
      "section": "MICROCONTEÚDOS",
      "kind": "Micro",
      "date": "Outubro 2026",
      "title": "Interesse",
      "role": "Microconteúdo / reflexão",
      "idea": "Questionar se o interesse acabou ou se acabou a necessidade de conquistar.",
      "format": "Micro Reel · 3–10s · ação + fala",
      "bodyLabel": "AÇÃO + FALA",
      "reviewLabel": "Microconteúdo",
      "text": "AÇÃO\nDelilton mexendo no celular. Bloqueia a tela e olha para a câmera.\n\nFALA\n“Talvez você não tenha perdido o interesse. Talvez só tenha parado de precisar conquistar aquela pessoa.”\n\nFIM."
    },
    {
      "id": "M11",
      "displayId": "11",
      "section": "MICROCONTEÚDOS",
      "kind": "Micro",
      "date": "Outubro 2026",
      "title": "Planos cancelados",
      "role": "Microconteúdo / reflexão",
      "idea": "Transformar o alívio do cancelamento em uma pergunta sobre a própria sobrecarga.",
      "format": "Micro Reel · 3–10s · ação + fala",
      "bodyLabel": "AÇÃO + FALA",
      "reviewLabel": "Microconteúdo",
      "text": "AÇÃO\nDelilton fecha o notebook ou agenda, relaxa na cadeira e olha para a câmera.\n\nFALA\n“Se planos cancelados sempre trazem alívio… talvez o problema não seja o plano.”\n\nFIM."
    },
    {
      "id": "M12",
      "displayId": "12",
      "section": "MICROCONTEÚDOS",
      "kind": "Micro",
      "date": "Outubro 2026",
      "title": "Terapia",
      "role": "Microconteúdo / reflexão",
      "idea": "Fazer a pessoa questionar o que evita levar para a própria terapia.",
      "format": "Micro Reel · 3–10s · ação + fala",
      "bodyLabel": "AÇÃO + FALA",
      "reviewLabel": "Microconteúdo",
      "text": "AÇÃO\nDelilton folheando um livro ou caderno. Para em uma página.\n\nFALA\n“E se aquilo que você não consegue contar na terapia for justamente o que precisa entrar nela?”\n\nFIM."
    }
  ]
};
